cmake_minimum_required(VERSION 3.23)
project(minishell C)

set(CMAKE_C_STANDARD 11)

include_directories(.)
include_directories(lib-pipex)
include_directories(lib-pipex/ft_printf)
include_directories(lib-pipex/get_next_line)
include_directories(libft)

add_executable(minishell
        builtins/cd.c
        builtins/echo.c
        builtins/env.c
        builtins/exit.c
        builtins/pwd.c
        lib-pipex/ft_printf/ft_printf.c
        lib-pipex/ft_printf/ft_printf.h
        lib-pipex/ft_printf/ft_printmemory.c
        lib-pipex/ft_printf/ft_putbase10_plus.c
        lib-pipex/ft_printf/ft_putchar_fd.c
        lib-pipex/ft_printf/ft_putnbr_fd.c
        lib-pipex/ft_printf/ft_putstr_fd.c
        lib-pipex/ft_printf/ft_strlen.c
        lib-pipex/get_next_line/get_next_line.c
        lib-pipex/get_next_line/get_next_line.h
        lib-pipex/get_next_line/get_next_line_utils.c
        lib-pipex/argument_processing.c
        lib-pipex/init_utils.c
        lib-pipex/path_finding.c
        lib-pipex/pipex.c
        lib-pipex/pipex.h
        lib-pipex/process_utils.c
        lib-pipex/stdin_parsing.c
        lib-pipex/utils.c
        libft/ft_atoi.c
        libft/ft_bzero.c
        libft/ft_calloc.c
        libft/ft_isalnum.c
        libft/ft_isalpha.c
        libft/ft_isascii.c
        libft/ft_isdigit.c
        libft/ft_isprint.c
        libft/ft_isspace.c
        libft/ft_itoa.c
        libft/ft_lstadd_back.c
        libft/ft_lstadd_front.c
        libft/ft_lstclear.c
        libft/ft_lstdelone.c
        libft/ft_lstiter.c
        libft/ft_lstlast.c
        libft/ft_lstmap.c
        libft/ft_lstnew.c
        libft/ft_lstsize.c
        libft/ft_memchr.c
        libft/ft_memcmp.c
        libft/ft_memcpy.c
        libft/ft_memmove.c
        libft/ft_memset.c
        libft/ft_putchar_fd.c
        libft/ft_putendl_fd.c
        libft/ft_putnbr_fd.c
        libft/ft_putstr_fd.c
        libft/ft_split.c
        libft/ft_strcat.c
        libft/ft_strchr.c
        libft/ft_strcmp.c
        libft/ft_strcpy.c
        libft/ft_strdup.c
        libft/ft_striteri.c
        libft/ft_strjoin.c
        libft/ft_strlcat.c
        libft/ft_strlcpy.c
        libft/ft_strlen.c
        libft/ft_strmapi.c
        libft/ft_strncmp.c
        libft/ft_strncpy.c
        libft/ft_strnstr.c
        libft/ft_strrchr.c
        libft/ft_strstr.c
        libft/ft_strtrim.c
        libft/ft_substr.c
        libft/ft_tolower.c
        libft/ft_toupper.c
        libft/get_output.c
        libft/libft.h
        interpreter.c
        m-shell.c
        minishell.h
        signals.c
        split.c
        utils.c)
